
const dictionary = {
    "a": "a",
    "a": "ein",
    "a": "oon",
    "absolutely": "epsomlootly",
    "ad": "klip",
    "all": "alla",
    "all of": "alla",
    "all right": "Dollripe-chus",
    "already": "al dente",
    "among": "entra",
    "and": "Epp",
    "anyway": "argo",
    "application": "zamplification",
    "at all": "da-doll",
    "B": "beau",
    "baby": "babbly",
    "beautiful": "baloontiful",
    "because": "porky",
    "been": "bin",
    "believe you": "crayola",
    "big": "da-wow",
    "big fraud": "sigismundo froyd",
    "bit": "pogo",
    "bliss": "blintz",
    "blissful": "blintzful",
    "book": "bop (da)",
    "bothering me": "bodami",
    "business": "beesnest",
    "but": "mock",
    "cake": "kick",
    "calm": "kalamari",
    "can I": "kennedy",
    "carry": "cargo",
    "chair": "chah",
    "clear": "clara",
    "coincidence": "co-inki-dance",
    "concentrate": "konsentreeren",
    "congratulations": "corngranulations",
    "correct": "perzacto",
    "cosmic satisfaction": "cosmogrottifee-kotsee-ohneeya",
    "could": "kood",
    "data": "binformations",
    "day": "jar",
    "despair": "desperanto",
    "did I": "diddle-eye",
    "difficult": "Deep-feekal",
    "difficulties": "deep-feecountries",
    "divine": "divina",
    "don't": "doopa",
    "don't say": "donutsayev",
    "don't speak": "parladoop",
    "door": "iosadora ()",
    "down": "rok",
    "east": "oyster",
    "easy": "eedgy",
    "ecstasy": "extahz",
    "eight": "wait",
    "English": "Johnclease",
    "enter": "ventrica",
    "especially": "con cavyar",
    "etcetera": "et cinema",
    "eternity": "deepternity",
    "ever": "evva",
    "exactly": "attackly",
    "excuse": "squeegie",
    "face": "veazle (da)",
    "fantastic": "flantastico",
    "fasten": "boggle",
    "feel": "sensa",
    "felt": "felta",
    "female": "vittamin",
    "finger": "linkage",
    "finger": "vinci",
    "first": "feersta (di)",
    "first": "feersten (di)",
    "for": "forest",
    "for me": "formeeka",
    "for the": "fordham",
    "form": "forum",
    "fraud": "froyd",
    "from here": "frontier",
    "from the": "fonda",
    "fun": "flan",
    "future": "furniture",
    "galosh": "gosh",
    "gave me": "gabriel",
    "get my": "getmi",
    "gift": "grift",
    "good": "bell",
    "good": "bleeny",
    "good": "gold",
    "grand": "gland",
    "great": "krakajak",
    "great": "Zoopa",
    "great": "Zoopa mit noodel",
    "hand": "anda (di)",
    "hand bag": "handberger",
    "happiness": "feleetze-totsee-ohneeya",
    "harmony": "armoneea",
    "has been": "long wharf",
    "have": "doppa",
    "he": "en",
    "hearts": "hartz",
    "here": "cheer",
    "here is": "voila-dimir",
    "honey": "shantz",
    "how are": "harvard",
    "how do you say": "howardjohnson",
    "I": "iago",
    "I didn't": "deedeena",
    "I'll give": "melgibson",
    "icing": "Ives-in",
    "iff": "six",
    "important": "importantay",
    "in": "en",
    "in love with": "amorphous",
    "in the": "enda",
    "indeed": "Indeedly-dee",
    "indeed": "forsoot",
    "inspiration": "inspermation",
    "it": "da",
    "it's yours": "estyuris",
    "just a minute": "moooment",
    "kiss": "kooch",
    "language": "linkwa (da)",
    "learn": "lick",
    "left": "eedon",
    "leg": "jamba",
    "lesson": "shantz",
    "let me": "lassmi",
    "lips": "volvos (da)",
    "listen": "nintendo",
    "little": "diddly",
    "lonely": "lornly",
    "love": "amamor",
    "male": "aspirin",
    "many": "mangey",
    "matter": "mattress",
    "me": "ya",
    "mean": "minksy",
    "melodious": "harmonika",
    "melody": "melodeea",
    "mess": "mezza (la)",
    "middle finger": "niro (di)",
    "mind": "tabooli (la)",
    "miss": "froyling",
    "money": "payola",
    "money": "geld",
    "morning": "morgen",
    "music": "moozheek",
    "my": "mi",
    "name": "klink",
    "narturally": "Natooraltissimississippimentay",
    "never": "nevva",
    "newspaper": "peeper (da)",
    "no": "oop",
    "not at all": "nikto",
    "not at all": "oopissima",
    "not at all": "absaloopdiloop",
    "nothing": "neekolas",
    "noze": "nozzle (da)",
    "occupation": "oxipation",
    "of": "di",
    "of course": "off corset",
    "okey-dokey": "okeefenoch-kee",
    "on the": "onda",
    "only": "osolomenito",
    "or": "orf",
    "orgasmic": "orgazmico",
    "others": "udders",
    "palm": "palma",
    "paradox": "para-dons",
    "past": "pasta",
    "pay": "pago",
    "people": "peepholes",
    "perfectly": "parfoom",
    "place": "platz (da)",
    "please": "police",
    "plus": "plotz",
    "poet": "poultice",
    "poetry": "poultry",
    "practice": "prentice",
    "present": "prison",
    "pretty": "bella",
    "problem": "problaymen",
    "proceed": "gwan (da)",
    "proof": "pravdaz",
    "pudding": "pudding",
    "question": "quisling",
    "ready": "raddly",
    "really": "veroushka",
    "really": "verismo",
    "relax": "lax",
    "repeat": "echo",
    "rest": "rest",
    "right": "rekt",
    "right": "ged",
    "right place": "rektplatz",
    "room": "Ram",
    "room": "rhoomba",
    "same": "dentrical",
    "savior": "slaveyard",
    "school": "kaka-daymee",
    "seatbelts": "zitzbells",
    "see or saw": "video",
    "seventh": "heventh",
    "sex": "slacks",
    "she": "dee",
    "shudder": "shoddra",
    "sit down": "plop",
    "small": "shmal",
    "so": "so",
    "song": "shlong",
    "speak": "parla",
    "speak it": "parlit",
    "speechless": "spinachless",
    "stick": "shtick",
    "strange": "blizzardo",
    "stutter": "Tonguestoppard",
    "such a": "socha",
    "suddenly": "sordenly",
    "supreem": "supreemka",
    "surely": "surrealismo",
    "tell you": "tellya",
    "tenses": "dances",
    "test": "testicle",
    "thanks": "angst",
    "that": "het",
    "that": "det",
    "that": "dot",
    "That's too bad": "Joe DiMaggio",
    "the": "da",
    "the": "di",
    "the": "la",
    "the": "dada",
    "the": "di",
    "there will be": "dolby",
    "they": "day",
    "think": "dinksdu",
    "thirty": "thirsty",
    "this": "hets",
    "this": "dis",
    "three": "free",
    "thrill": "frill",
    "thumb": "bamba",
    "to": "ta",
    "to": "tu",
    "together": "togandi",
    "tongue": "hoover (da)",
    "twenty": "vont",
    "two": "yu",
    "two-step": "jambo-ree",
    "understand": "badaba",
    "Unfortunately": "Alaska",
    "unite": "oonidevairsify",
    "universal": "looniversahl",
    "universe": "looniverse",
    "up": "enro",
    "very": "bonanza",
    "very": "molto",
    "very easy": "egsovereedgy",
    "very good": "da skool da fortnox",
    "very much in love with": "polymorphous",
    "wait": "varta",
    "walls": "valtz (da)",
    "want": "scoop",
    "want to": "vanta",
    "warn you": "vanya",
    "was": "wharf",
    "we": "wop",
    "welcome": "velcro",
    "welcome": "velcro",
    "what": "vot",
    "What": "vee",
    "what does this": "Votsdiss",
    "will": "barf",
    "will be": "barf",
    "with": "mit",
    "wonder": "voonda",
    "word processor": "verboblender",
    "world": "voooold",
    "would be": "ifarf*",
    "wrong": "rrrong",
    "wrong place": "rongplatz",
    "yes": "ding",
    "you": "yu",
    "you": "du",
    "you": "du",
    "you": "dusa",
    "you": "du",
    "you (plural)": "doobly",
    "you are": "klahtoo",
    "you": "Ya",
    "your": "dai",
    "true": "versimo"
};

function translateWord() {
    const inputText = document.getElementById('inputText').value.toLowerCase();
    const resultDiv = document.getElementById('result');

    // Split input into words by spaces and punctuation
    const words = inputText.split(/\s+/);

    // Translate each word individually
    const translatedWords = words.map(word => {
        if (dictionary[word]) {
            return dictionary[word];
        } else if (Object.values(dictionary).includes(word)) {
            // If the word is in Unamanda, find the English translation
            return Object.keys(dictionary).find(key => dictionary[key] === word);
        } else {
            return word;  // If no translation is found, leave the word as it is
        }
    });

    // Join the translated words back into a sentence
    resultDiv.textContent = `Translation: ${translatedWords.join(' ')}`;
}
